[book]
authors = ["Emile Cadorel"]
language = "eo"
multilingual = false
src = "src"
title = "Ymir Tour"

[output.html]
additional-css = ["js/custom.css"]
additional-js = ["js/custom.js"]
site-url="/eo/"